name: PHP Unit Testing

on:
  push:
    branches:
      - main  # Adjust the branch name as needed
  pull_request:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4  # Adjust the PHP version as needed

      - name: Make vendor/bin/phpunit executable
        run: chmod +x vendor/bin/phpunit

      - name: Run PHPUnit tests
        run: vendor/bin/phpunit
